name: Continuous Integration

on:
  push:
    branches:
      - main
      - test-github-action
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install flake8 black

      - name: Lint code
        run: |
          black --check --line-length 80 app
          flake8 --exclude=__init__.py app

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and run services
        run: docker-compose -f deployment/docker-compose.yaml up -d

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r deployment/requirements.txt

      - name: Run tests
        run: pytest tests
